# Generated by Django 4.1 on 2023-01-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('rollno', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('class_in', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('Institute', models.CharField(max_length=100)),
                ('current_sem', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=10)),
                ('createdat', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
