# Generated by Django 4.1 on 2023-01-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
