# Generated by Django 4.1 on 2023-01-03 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_alter_user_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recognition.user')),
                ('present', models.BooleanField()),
                ('todaysdate', models.DateField(auto_now_add=True)),
                ('currenttime', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(choices=[('TCS', 'TCS'), ('SE', 'SE'), ('IP', 'IP'), ('CN', 'CN'), ('DWM', 'DWM')], max_length=20)),
            ],
        ),
    ]
